image: docker:stable

stages:
    - build

variables:
  CONTAINER_TEST_IMAGE: gagan0123/dev:wpunit-$CI_COMMIT_REF_SLUG

before_script:
   - docker info

build:
   stage: build
   script:
     - cd php/7.3 && docker build --pull -t $CONTAINER_TEST_IMAGE .
     - docker push $CONTAINER_TEST_IMAGE